### ISSUE TITLE
Docs: Suggestion to include a FAQs.md

### ISSUE THREAD

**Issue by W7ebere** [ENHANCE-PET/MOOSE#113]
**Is your feature request related to a problem? Please describe.**

It would be benificial to have a frequently asked section for MOOSE, so that one can immediately find solutions.

**Describe the solution you'd like**
I would propose to use FAQ.md file to list down most commonly faced issues and their corresponding solutions.

**Comment by LalithShiyam** [comment]
@all-contributors please add @W7eber for adding docs

**Comment by LalithShiyam** [comment]
@all-contributors please add @W7ebere for adding docs

**Comment by LalithShiyam** [comment]
@W7ebere thanks for your contribution - welcome to MOOSE!
