### ISSUE TITLE
BUG: requests.exceptions.ProxyError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by ArmsOpen** [ENHANCE-PET/MOOSE#128]
Hi! I have followed your work for a while and I express my appreciation for your work. I met some problems when using MOOSE 2.0 to  do 3D-CT medical segmentation in a Python project. The error goes as follows:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='enhance-pet.s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /moose/clin_ct_organs_23062023.zip (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

My Python codes are as follows (just as the usage guide you give in README.md):

 `
from moosez import moose

model_name = 'clin_ct_organs'
input_dir = 'D:\moose-test\input'
output_dir = 'D:\moose-test\output'
accelerator = 'cuda'
moose(model_name, input_dir, output_dir, accelerator)
`

I'm a newbie at programming. I tried to configure the environment to your guide but the error still occurs. It seems that there's a problem with getting access to the proxy server. I'm not sure if there is a problem with my proxy or I don't have the right to visit your proxy.

I find that in all the other issues there's not one that describing the problems same as mine, so I open this issue. I would be grateful if you can help me.

**Comment by LalithShiyam** [comment]
Hi @ArmsOpen many thanks for the kind words. By any chance, are you trying to run this from your university network? When I see the error 'ProxyError', it can be a firewall issue of the University or hospital. 

Tagging these gentlemen @mprires and @Keyn34 as they are seasoned bug-squashers. BTW @Keyn34 didn't the LITO group have similar issues? do you know how they solved it?

**Comment by ArmsOpen** [comment]
I'm wondering if there's something wrong with accessing the model remotely. Could you send me the model 'clin_ct_organs' directly if that's okay?

**Comment by mprires** [comment]
Hey @ArmsOpen ! Usually this problem is on your end. If you give me your email I can send you a filsender link with the model and a tutorial on where to place it :)

**Comment by LalithShiyam** [comment]
Is this sorted @mprires and @ArmsOpen? If yes - may I close it?

**Comment by mprires** [comment]
Still waiting for @ArmsOpen contact

**Comment by LalithShiyam** [comment]
closing this as this is a firewall issue :)
