### ISSUE TITLE
BUG: calling preclin_ct_legs model  

### ISSUE THREAD

**Issue by Samnonstop** [ENHANCE-PET/MOOSE#131]
**Describe the bug**
When running the task "preclin_ct_legs" with a whole-body CT, MOOSE failed during resampling due to a value error in the map_blocks function as below:

![image](https://github.com/ENHANCE-PET/MOOSE/assets/47909596/8dd35032-2ef2-48e6-b3b0-9fec11c3b4ed)

If I explicitly set "dtype=np.float64" in the da.map_blocks function, the error message would change to be like this:

![image](https://github.com/ENHANCE-PET/MOOSE/assets/47909596/0b475b3d-80de-4466-90de-a6c32e6d795e)

**Expected behavior**
Successfully segment the image.

**Environment**
 - OS: Windows 10, 128GB RAM
 - Python: 3.11.9 installed by Anaconda
 - Version: Moose2.0

**Additional context**
My file for the whole-body CT is ~100MB in NIfTI format, and it can be segmented by task "clin_ct_organs". Not sure why changing the task would result in failure.

Thank you for your generous help!

**Comment by Keyn34** [comment]
Hi @Samnonstop. 

Is your CT a whole-body human scan or a mouse scan? The preclinical models (`preclin_*`) are designated for segmenting mice. 
Also, what is your image's geometry (matrix and voxel size)? Preclinical imaging has a much higher resolution than conventional imaging. So, it would make sense that you run out of memory when attempting to resample the image, as the preclinical models use a smaller target resolution for resampling.

Have you also been able to check the RAM consumption of the process?

**Comment by LalithShiyam** [comment]
Hi @Samnonstop, 

If I understand you right, `clin_ct_organs` works on your dataset and `preclin_ct_legs` doesn't. So I assume you are using human datasets and not mice datasets. As @Keyn34 pointed out - `preclin_` models are meant for mice and not for humans. 

Cheers,
Lalith

**Comment by LalithShiyam** [comment]
@Samnonstop is this resolved? May I close this?

**Comment by Samnonstop** [comment]
> Hi @Samnonstop.
> 
> Is your CT a whole-body human scan or a mouse scan? The preclinical models (`preclin_*`) are designated for segmenting mice. Also, what is your image's geometry (matrix and voxel size)? Preclinical imaging has a much higher resolution than conventional imaging. So, it would make sense that you run out of memory when attempting to resample the image, as the preclinical models use a larger target resolution for resampling.
> 
> Have you also been able to check the RAM consumption of the process?


Thank you for the reply. I understand that I had used the mice segmentation model for human scan by mistake. This problem is solved, thanks!
