### ISSUE TITLE
Moose could not start

### ISSUE THREAD

**Issue by wolebode** [ENHANCE-PET/MOOSE#137]
Hello, I tried installing moose following the instructions in the github. It says successfully installed. But when I try running moosez, it gives this error message:

OSError: [WinError 126] The specified module could not be found. Error loading "....\moose-env\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies

I can confirm that this file "fbgemm.dll" is present in the folder.
Please, any help will be appreciated. 

![image](https://github.com/user-attachments/assets/111953dd-4aba-440a-a3a9-e4b7c902d4f8)
![Capture](https://github.com/user-attachments/assets/1b7689db-4ce5-4a7d-9a18-39cb0411e4ae)

**Comment by LalithShiyam** [comment]
Hi @wolebode 

This error is new for me as well. A search in the PyTorch forum pointed me towards this thread: https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

I think this is from torch and not really from moose. 

The thread contains some solutions. Kindly have a look. 

@mprires @Keyn34 tagging you for visibility. 

Cheers,
Lalith

**Comment by mprires** [comment]
Hi @wolebode 

It appears you're on a Windows machine. Please note that PyTorch needs to be manually installed before installing MOOSE on Windows. We've encountered issues on another tool where skipping this step caused errors. 
Could you confirm that you've installed PyTorch following the instructions at https://pytorch.org/get-started/locally/ ?

Kind regards,
Manel

**Comment by wolebode** [comment]
Thanks so much for your prompt response.

Yes, I installed PyTorch using the command "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
when that didn't work, I then started all over again and installed the CPU version using "pip3 install torch torchvision torchaudio"

Is that right?

**Comment by Keyn34** [comment]
@wolebode, could you give us more information on the system you are trying MOOSE on? Which GPU, CPU, and Python Version are you using? 

Also, I saw from the terminal that you tried to do `moosez -d`. Is this correct, or was the command trimmed due to the error?

Thanks in advance!

**Comment by wolebode** [comment]
Here are the details:

CPU - Intel(R) Core(TM) i9-14900K
GPU - NVIDIA RTX 4000 Ada Generation
Python - 3.10.0

About the command, it gives the same error whatever I type, even when I type "moosez -h" for help

**Comment by wolebode** [comment]
Thanks everyone. I have been able to resolve the issue. 
Invariably, it appeared that PyTorch was not properly installed. So, I installed CUDA NVIDIA, and the issue was fixed.

Thanks once again

**Comment by LalithShiyam** [comment]
@wolebode fantastic - keep us posted, if you are pleased with the results from MOOSE. And we are happy to help :)

**Comment by wolebode** [comment]
I will do.
Thanks so much. You guys are awesome.

**Comment by wolebode** [comment]
Hello, it's me again:
I'm trying to run moose on a CT dicom file, and it's giving this error:
![image](https://github.com/user-attachments/assets/ce97a4e9-7245-4d4a-8542-c372bfdea9d8)
I tried remaining all files to have CT1, CT2...CT86 but I don't know if there's anything else I need to do to make it compliant

**Comment by LalithShiyam** [comment]
Hi there, it runs in batch, can you send me the screenshot of your folder structure, it should be 

All-cts
|_ct_1
|_ct_2
|_ct_3

`and the input is moosez -d <path_to_All-cts> -m clin_ct_organs`

**Comment by wolebode** [comment]
![image](https://github.com/user-attachments/assets/44742104-e097-4b31-9e0e-a28510cdf23f)

**Comment by LalithShiyam** [comment]
Hi @wolebode, this folder should be nested inside another folder, and you should pass that folder as the input. Because moose runs in batches. Right now you are passing one of the subjects directly to moose.

**Comment by wolebode** [comment]
Thanks so much. It works!
