### ISSUE TITLE
There is a problem using the module：clin_ct_body_composition  

### ISSUE THREAD

**Issue by yusun19** [ENHANCE-PET/MOOSE#153]
![图片1](https://github.com/user-attachments/assets/b9e9a6df-f7d5-40a1-bbaf-9b8172b86679)
I apologize for bothering you again. When I run this module, I encounter the aforementioned error. However, when using the same data with other modules, it runs normally. Regardless of whether I use the command line or Python to call it, I get the same error. Therefore, I would like to ask if there is an issue with the model. I look forward to your response.

**Comment by mprires** [comment]
Hi @yusun19. Could you please provide more details? What Python version are you on? Can you Run the command "pip freeze" and tell me the nnunet version? Did you install moose via pip? 

Kind regards,
Manel

**Comment by Keyn34** [comment]
@yusun19, please navigate to the directory where you want to run moose and check the `moosez-v3.0.0_<date>.log` file. You should find an entry regarding the custom trainer at the beginning of the file (search for `Custom trainer`). What does it say for you? 

Thanks

**Comment by yusun19** [comment]
nnunetv2==2.5.1，python=3.10  Yes,I used pip to install moose

**Comment by Keyn34** [comment]
@yusun19 did you find the `.log`-file?

**Comment by yusun19** [comment]
Custom trainer: Could not find custom trainer file: /home/sunyn/anaconda3/envs/moose/lib/python3.10/site-packages/moosez/nnUNet_custom_trainer/MOOSE_custom_trainers.py

**Comment by mprires** [comment]
Are you using a conda environment? Can you try to create the environment with: 
`python3 -m venv moose-env`, please

**Comment by yusun19** [comment]
I use the Anaconda .Can I ?

**Comment by Keyn34** [comment]
Yes, you can, and it should work with Anaconda as well. 

Create a separate virtual environment with Anaconda and install `moosez `there.

**Comment by yusun19** [comment]
![1729737079538](https://github.com/user-attachments/assets/418132c4-1d3e-44cf-a2a9-abf5f54ec930)
I seem to be experiencing network issues, which have resulted in an incomplete download of the model.How can I download the model myself and call it from my local machine?

**Comment by Keyn34** [comment]
Do you have any idea why you are experiencing these issues? 

I just checked, and all our links are working fine. 

You could check out the [`MODEL_METADATA`](https://github.com/ENHANCE-PET/MOOSE/blob/ab2f2d90b79b383348c1013c7f180c6108212a17/moosez/models.py#L10) dictionary, use the links to download the models manually, unzip them and finally place them in the `models` folder of your virtual environment. 

However, this is not intended. It might be worthwhile to investigate why you are experiencing network errors.

**Comment by Keyn34** [comment]
Hi @yusun19, did it work out? Any news?

**Comment by yusun19** [comment]
Yes, I succeeded in the end; it was a network issue on my side. Thank you for your explanation, and thank you for such a great model!

**Comment by Keyn34** [comment]
Wonderful. Thank you for letting us know!
