### ISSUE TITLE
UserWarning on Mac: Cannot set number of intraop threads

### ISSUE THREAD

**Issue by alfab8ta** [ENHANCE-PET/MOOSE#155]
When running Moose v3 using MPS without the "herd" option, the following warning message appears for each processing step as attached. Segmentation completes successfully, but the recurring warning messages are distracting. Any suggestions for resolving this would be appreciated.

⠼ [1/59] Running prediction for CRC2410220125603_20241024 using clin_ct_organs.../Users/jaehl/moosez/lib/python3.10/site-packages/nnunetv2/inference/export_prediction.py:68: UserWarning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (Triggered internally at /private/var/folders/s7/5c5z_sgx0tjdcnnvph2pjqm00000gn/T/pip-req-build-oaybygzt/aten/src/ATen/ParallelNative.cpp:228.)
  torch.set_num_threads(old_threads)
⠋ [1/59] Running prediction for CRC2410220125603_20241024 using clin_ct_organs.../Users/jaehl/moosez/lib/python3.10/site-packages/nnunetv2/inference/export_prediction.py:68: UserWarning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (Triggered internally at /private/var/folders/s7/5c5z_sgx0tjdcnnvph2pjqm00000gn/T/pip-req-build-oaybygzt/aten/src/ATen/ParallelNative.cpp:228.)

.....

System:
Mac OS Sonoma 14.7
M3 Macbook / 36 GB RAM

**Comment by LalithShiyam** [comment]
Hi @alfab8ta, I have the same issues too. I tried it a bunch of times and I could never solve it. If you have any bright ideas. Please let me know. And don't worry too much about this, the inference will work but you will see these ugly messages... 

It has been annoying me for sometime; but I have no solution. 

Lalith

**Comment by alfab8ta** [comment]
Thank you for letting me know. Not a big problem as long as the inference works fine.

**Comment by LalithShiyam** [comment]
May I close it @alfab8ta, as I can't do much about it?

**Comment by alfab8ta** [comment]
Sure. Please do so. Thanks, @LalithShiyam .
