### ISSUE TITLE
Add warning message or early exit in clin_ct_body_composition model for missing L3 vertebrae

### ISSUE THREAD

**Issue by LalithShiyam** [ENHANCE-PET/MOOSE#160]
Description

The clin_ct_body_composition model in MOOSE looks for the L3 vertebrae in the CT image and segments the body composition around that vertebrae. If the L3 segment is not present in the field of view (FOV) of the CT, the process currently returns no segmentation without any warning or message. This leads to confusion as it doesn't indicate why no segmentation is produced.

Please add a warning message (PREDICT section) or implement an early exit in the model if the L3 vertebrae is not present (again with a warning print message), to improve the user experience. The message could inform the user that the L3 vertebrae is not present in the FOV, and therefore, no segmentation is produced.

**Comment by Keyn34** [comment]
Handled in #162
