### ISSUE TITLE
Improve Log Messages for Image Chunking When Image Matrix is Small

### ISSUE THREAD

**Issue by LalithShiyam** [ENHANCE-PET/MOOSE#161]
## Description 

The current log message "Image chunked to 1x1x1x1 chunks" is misleading when the image matrix is small. It could be interpreted as passing slices after chunking. A clearer message should be logged, such as "Image array is within f{chunking_threshold}, therefore passing as whole."

**Comment by LalithShiyam** [comment]
P.S: The chunking logs in general are not clear, need to rework.

**Comment by Keyn34** [comment]
Handled in #162
