### ISSUE TITLE
BUG:The results of  'clin_ct_body_composition' cannot include the whole body, only part of it works

### ISSUE THREAD

**Issue by Leonjr98** [ENHANCE-PET/MOOSE#164]
**Describe the bug**
When 'clin_ct_body_composition' is performed with whole-body CT, only a very small portion of the abdomen will yield results. All other models can be segmented normally.

**Desktop (please complete the following information):**
 - OS: Linux x86_64
 - Version : Moosez 3

**Comment by LalithShiyam** [comment]
Hi @Leonjr98 

The model is performing as intended. Body composition is usually measured around L3 vertebrae and it is a widely accepted standard. Verifying 1700 cases of total body subcutaneous and visceral fat, muscle is a non trivial task as there are lot of misclassifications to correct for. Therefore, we made sure all our 1.7k datasets have an accurate segmentation around the L3 vertebrae during training. And as a result, our inference also has this region only. 

Cheers,
Lalith

**Comment by Leonjr98** [comment]
> Hi @Leonjr98
> 
> The model is performing as intended and it is NOT a bug. Body composition is usually measured around L3 vertebrae and it is a widely accepted standard. Verifying 1700 cases of total body subcutaneous and visceral fat, muscle is a non trivial task as there are lot of misclassifications to correct for. Therefore, we made sure all our 1.7k datasets have an accurate segmentation around the L3 vertebrae during training. And as a result, our inference also has this region only.
> 
> Cheers, Lalith
> 
> @Keyn34 did we include a display message for this model somewhere, where we explain this? I think we should definitely do this.

Thank you for your reply. I was wondering if you have any plans to do the whole Body, not just around L3, Body composition

**Comment by Leonjr98** [comment]
> Hi @Leonjr98
> 
> The model is performing as intended and it is NOT a bug. Body composition is usually measured around L3 vertebrae and it is a widely accepted standard. Verifying 1700 cases of total body subcutaneous and visceral fat, muscle is a non trivial task as there are lot of misclassifications to correct for. Therefore, we made sure all our 1.7k datasets have an accurate segmentation around the L3 vertebrae during training. And as a result, our inference also has this region only.
> 
> Cheers, Lalith
> 
> @Keyn34 did we include a display message for this model somewhere, where we explain this? I think we should definitely do this.

Thank you for your reply. I was wondering if you have any plans to do the whole Body, not just around L3, Body composition

**Comment by Leonjr98** [comment]
> Hi @Leonjr98
> 
> We could do it - it just won't be accurate. Getting it accurate would cost us a lot of money (we pay for our annotations). Therefore we don't see the total body version happening.
> 
> Cheers, Lalith

I have no further questions. Finally, thank you very much for your reply
