### ISSUE TITLE
FEAT: PET and CT Image Alignment with Affine Transformation

### ISSUE THREAD

**Issue by LalithShiyam** [ENHANCE-PET/MOOSE#98]
### Description
Requesting the reintroduction and enhancement of affine alignment for PET and CT images, a feature from MOOSE v1.0. This was requested [here!](https://github.com/QIMP-Team/MOOSE/issues/97#issuecomment-1976963138) This feature should align PET and CT images, output the aligned CT, and produce a multilabel segmentation aligned with the PET image. The primary use case is to facilitate the extraction of activity concentration from aligned multimodal images.

### Justification
Accurate alignment and segmentation are critical for combining anatomical and functional imaging data, essential for precise activity concentration analysis in research and clinical applications.

### Requirements
1. **Affine Alignment**: Implement an improved affine alignment algorithm for PET and CT images (reuse from FALCON)
2. **Output Aligned Images**: Provide the aligned CT image as output.
3. **Multilabel Segmentation**: Output a multilabel segmentation map aligned with the PET image.
4. **Extract activitiesn**: Use the multilabel segmentation map to extract activities from the PET image.

### Requested by 
Tagging @vikashg as they have requested the creation of this feature request to address their specific needs.

**Comment by vikashg** [comment]
Hi @LalithShiyam, 
Thanks for the feature request.
So if I understand correctly Falconz is the tool that was used for registration and MOOSE v1.0 had a wrapper on it. 
BTW kudos to the team for coming up with acronyms :)

**Comment by LalithShiyam** [comment]
Hi @vikashg,
Haha - I will convey it to the team! 
Exactly, we will be using FALCON :D! 
Also, leave us a star - if you find our work useful.
Cheers,
Lalith

**Comment by LalithShiyam** [comment]
Included in moosev3. 🎉
